### ISSUE TITLE
does not work on web mobile

### ISSUE THREAD

**Issue by derrick56007** [drogel/keyboard_dismisser#5]
it seems that this package does not work on web mobile; tapping outside of the textfield after wrapping the page in KeyboardDismisser() does not dismiss the keyboard

**Comment by drogel** [comment]
Hi @Derrick56007,

First of all thanks for using the package and for taking the time to open this issue. I have been taking a look at it and I would need more information on the exact conditions in which you observed that the package stopped working. I have built the example app from the package for the web using `$ flutter build web`, without null safety, and using the following Flutter version:

```
[√] Flutter (Channel beta, 1.26.0-17.6.pre)
    • Flutter version 1.26.0-17.6.pre
    • Framework revision a29104a69b (4 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)
 ```

you can take a look at the `main.dart` of this example app [here](https://github.com/drogel/keyboard_dismisser/blob/master/example/lib/main.dart). I have pushed the build to my GitHub pages to test it in different environments. You can open it directly in your mobile browser [here](https://drogel.github.io/keyboard_dismisser_example/#/). 

The keyboard dismisser seems to work fine, I have tried the example app that I just described on mobile Safari and Chrome, and in both browsers the keyboard is dismissed correctly when tapping or swiping down outside of the text field (that is what the example app is supposed to do).

So I need to know more about the details of your implementation in order to help you with the issue. A minimal code sample that reproduces the issue you describe would be ideal for me to find out if there is something wrong with the package.

Thanks a lot!

**Comment by derrick56007** [comment]
@drogel 

Thanks for the followup. I took a further look at my setup and realized the keyboard dismisser needed to be the parent of the scaffold; it works!
