### ISSUE TITLE
On Hide Keyboard Function

### ISSUE THREAD

**Issue by phuhungtran** [drogel/keyboard_dismisser#8]
How to know when the keyboard is hidden?
I think this plugin needs an onHideKeyboard function.
Will you update this?

**Comment by drogel** [comment]
Hi @phuhungtran, 

Thanks for your comment and for using the package. It would be interesting to have such a callback, but if I implemented it I would need to either depend on or rewrite the functionality already encapsulated in the [flutter_keyboard_visibility](https://pub.dev/packages/flutter_keyboard_visibility) package. 

This package provides you with a few callbacks so that you can react to keyboard visibility changes. It lets you build your widget tree based on whether or not the keyboard is visible, and perform stuff whenever the keyboard hides. 

I think it wouldn't make sense to add such a feature to `keyboard_dismisser` when there are ways to do the same thing already out there in the wild. You can always build your own wrapper around my package and `flutter_keyboard_visilibity` to have them all in a single widget if you want. When it comes to reusable packages, the more specialized, the better, in my opinion.

Hope that leads you towards a solution to your problem. Thanks!

**Comment by phuhungtran** [comment]
> Hi @phuhungtran,
> 
> Thanks for your comment and for using the package. It would be interesting to have such a callback, but if I implemented it I would need to either depend on or rewrite the functionality already encapsulated in the [flutter_keyboard_visibility](https://pub.dev/packages/flutter_keyboard_visibility) package.
> 
> This package provides you with a few callbacks so that you can react to keyboard visibility changes. It lets you build your widget tree based on whether or not the keyboard is visible, and perform stuff whenever the keyboard hides.
> 
> I think it wouldn't make sense to add such a feature to `keyboard_dismisser` when there are ways to do the same thing already out there in the wild. You can always build your own wrapper around my package and `flutter_keyboard_visilibity` to have them all in a single widget if you want. When it comes to reusable packages, the more specialized, the better, in my opinion.
> 
> Hope that leads you towards a solution to your problem. Thanks!

Oh I got it.
Thank you @drogel .
